apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
data:
  sshd_config: |
    PasswordAuthentication no
    ChallengeResponseAuthentication no
    UsePAM no
  authorized_keys: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDlh4xBpH7qdpoWyOH7fGqeoRP5TBdgt4amYTSs6bywXTzfYoicrRIZ/9EgqZwGAbOgg+A5OjVMdPPAM6EigXd3xlnZspzm5cAkJFhfuTHqNsT0aD+vC9sxDwwQAm5e1B9mjvbH9AK4bVRo+2NNHPMZ1/W8DYG5O97Ti00ax0Az2hIiwpWmKk51pK4/e/gLEULv1iq+zUK0UEEVmAanlvzQ6aYKIFujUUsCxmK8kTCCKhAvt5gusiwuPWPh5uDdwN0PtJB+aNSURWHK/MuVHbBJ+K2kPFSwVJ1lHoWUG0u/FM2N/+zmZkfCMLr36PltYpk98bvyGxDl8NqoBlNZdmHtsl+NPCDDe5lZPlhn2KJdtScr61LpGnilIx+8HCXQYQU5SW9wjTwIkc/YSSrKvANfR3niMMLhjbjJgDqRFLIzlxLeKBfFz7g9O8fJjCRDmXtVXSUXgit5M1t+NWX6/D5cVkVJzNtCFcdEec/NoPttK/wfzg0QsYRbsER4n62S9NQY1q6K1aGHvZjE64SZ+zNwSbaHDN7n5/3UpZOV0LxogAZ4NfQ/hLdHOLo8FgI9pPYLveOoH0RXb7pQlr1Bwt7le+NTZlb58iev0ooRM3Qvq1BC08tWNQmPW306sUDEcjTqBttprtOiL4ASfpKn1RHf7GfQJA8E7/w74BkKsAJ8WQ== sonalis@sonalis
