apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubuntu
  name: ubuntu
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
        - image: ubuntu
          name: ubuntu
          ports:
            - containerPort: 22
          volumeMounts:
            - name: ssh-volume
              subPath: sshd_config
              mountPath: /etc/ssh/sshd_config
            - name: ssh-volume
              subPath: authorized_keys
              mountPath: /root/.ssh/authorized_keys
      volumes:
        - name: ssh-volume
          configMap:
            name: ssh-config
