apiVersion: v1
kind: Service
metadata:
  labels:
    app: ubuntu
  name: ubuntu
  namespace: default
spec:
  ports:
    - port: 22222
      targetPort: 22
  selector:
    app: ubuntu
  type: LoadBalancer
