apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    env: prod
spec:
  replicas: 8
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: HELLO
              value: WORLDS
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "2"
