apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-config
data:
  sshd_config: |
    PasswordAuthentication no
    ChallengeResponseAuthentication no
    UsePAM no
    PermitRootLogin yes
  authorized_keys: >
    ssh-rsa
    AAAAB3NzaC1yc2EAAAADAQABAAACAQDlh4xBpH7qdpoWyOH7fGqeoRP5TBdgt4amYTSs6bywXTzfYoicrRIZ/9EgqZw/e/gLEULv1iq+zUK0UEEVmAanlvzQ6aYKIFujUUsCxmK8kTCCKhAvt5gusiwuPWPh5uDdwN0PtJB+aNSURWHK/MuVHbBJ+K2kPFSwVJ1lHoWUG0u/FM2N/+zmZfCMLr36PltYp98bvyGxDl8NqoBlNZdmHtsl+PCDDe5lZPlhn2KJdtScr61LpGnilIx+HCXQYQU5SW9wjTwIkc/YSSrKvANfR3niMMLhbjJgDqXgit5M1t+NWX6/D5cVkVJzNtCFcdEecNoPttK/wfzg0QsYRbsER4n62S9NY1q6K1aGHvZjE64SZ+zwSbaDN7n5/3UpZO0LxogAZ4fQ/hLdHOLo8FgI9pYLveOoH0RXb7pQlr1Bwt7l+NTZlb58iev0ooRM3Qvq1BC0tWNQmPW306sUDEcjTqBttprtOiL4SfpKn1RHf7GfQJA8E7/w74kKsAJ8WQ==
    sonalis@sonalis
