apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
  namespace: testkctl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:

    metadata:
      labels:
        app: test
    spec:
      containers:
        - image: cerebro31/monokle-helloworld:1.5
          name: test
          ports:
            - containerPort: 22
          volumeMounts:
            - name: ssh-volume
              subPath: sshd_config
              mountPath: /etc/ssh/sshd_config
            - name: ssh-keys
              subPath: authorized_keys
              mountPath: /root/.ssh/authorized_keys
      volumes:
        - name: ssh-volume
          configMap:
            name: ssh-config
        - name: ssh-keys
          secret:
            secretName: ssh-secret
            defaultMode: 0644
            items:
              - key: ssh-public-key
                path: authorized_keys
                mode: 0600
